"""Spatial traffic-assignment endpoint (SPEC §7.7).

``POST /spatial`` takes a compiled Policy DSL and returns a peak-hour static
traffic assignment over the Auckland road network: congested link flows, cordon
inflow, network vehicle-hours, gravity job accessibility and a per-zone road-CO₂
dispersion proxy — each as World A (baseline) vs World B (policy).

Car demand is generated by the *same* deterministic agent-based mode-choice model
as ``/simulate`` — only the commuters who still choose to drive are loaded onto
the network — then routed to an approximate user equilibrium (MSA + BPR). Every
number is Simulated and produced without an LLM (SPEC §34); the spatial
assumptions are documented Estimated inputs surfaced under ``params``.
"""

from __future__ import annotations

from fastapi import APIRouter
from pydantic import BaseModel, Field

from ..policy.dsl import PolicyDSL
from ..spatial.model import build_spatial_report
from ..spatial.schema import SpatialReport

router = APIRouter(prefix="/spatial", tags=["spatial"])


class SpatialRequest(BaseModel):
    """Input to ``POST /spatial``."""

    policy: PolicyDSL = Field(description="Compiled Policy DSL (from /policy/compile).")


@router.post("", response_model=SpatialReport,
             summary="Assign policy car demand to the road network (SPEC §7.7)")
def spatial(req: SpatialRequest) -> SpatialReport:
    """Return the spatial traffic-assignment report for the policy (SPEC §7.7)."""
    return build_spatial_report(req.policy)
