/**
 * City geometry loader for the 3D map (SPEC §17/§27).
 *
 * The Auckland world state (zones / roads / CBD cordon) is bundled as
 * static GeoJSON under `public/city/` so the map renders even before the backend
 * exposes a geometry endpoint. If the backend later serves `/city/*.geojson`
 * (same filenames), point `NEXT_PUBLIC_CITY_BASE_URL` at it and the loader will
 * prefer that. The geometry is world *input*, tagged Synthetic — it is not a
 * simulation result and no LLM produced it (SPEC §34).
 */

import type {
  Feature,
  FeatureCollection,
  LineString,
  Polygon,
} from "geojson";

/** Where the GeoJSON assets live. Defaults to the bundled copies in `public/`. */
export const CITY_BASE_URL =
  process.env.NEXT_PUBLIC_CITY_BASE_URL ?? "/city";

export interface ZoneProps {
  zone_id: string;
  row: number;
  col: number;
  category: string;
  land_use: string;
  is_cbd: boolean;
  area_km2: number;
  population: number;
  households: number;
  jobs: number;
  centroid_lon: number;
  centroid_lat: number;
}

export interface RoadProps {
  link_id: string;
  from_zone: string;
  to_zone: string;
  road_class: string;
  lanes: number;
  length_km: number;
  capacity_veh_per_hr: number;
  free_flow_speed_kmh: number;
  crosses_cordon: boolean;
  interior_cbd: boolean;
}

export interface CbdProps {
  name: string;
  zone_ids: string[];
  description: string;
}

export type ZoneFeature = Feature<Polygon, ZoneProps>;
export type RoadFeature = Feature<LineString, RoadProps>;
export type CbdFeature = Feature<Polygon, CbdProps>;

export interface CityManifest {
  title: string;
  provenance: string;
  center: { lat: number; lon: number };
  grid: { rows: number; cols: number; cell_km: number };
  counts: Record<string, number>;
  totals: Record<string, number>;
}

export interface CityGeometry {
  zones: FeatureCollection<Polygon, ZoneProps>;
  roads: FeatureCollection<LineString, RoadProps>;
  cbd: CbdFeature;
  manifest: CityManifest;
}

async function fetchJson<T>(path: string, signal?: AbortSignal): Promise<T> {
  const res = await fetch(`${CITY_BASE_URL}/${path}`, {
    signal,
    cache: "force-cache",
  });
  if (!res.ok) {
    throw new Error(`Failed to load ${path}: HTTP ${res.status}`);
  }
  return (await res.json()) as T;
}

/** Load all city geometry needed by the map in parallel. Throws on failure. */
export async function loadCityGeometry(
  signal?: AbortSignal,
): Promise<CityGeometry> {
  const [zones, roads, cbd, manifest] = await Promise.all([
    fetchJson<FeatureCollection<Polygon, ZoneProps>>("zones.geojson", signal),
    fetchJson<FeatureCollection<LineString, RoadProps>>("roads.geojson", signal),
    fetchJson<CbdFeature>("cbd_polygon.geojson", signal),
    fetchJson<CityManifest>("manifest.json", signal),
  ]);
  return { zones, roads, cbd, manifest };
}

// ---------------------------------------------------------------------------
// Origin–destination trip matrix (synthetic world input, SPEC §34)
// ---------------------------------------------------------------------------

export interface OdPair {
  origin: string;
  destination: string;
  daily_person_trips: number;
  distance_km: number;
  dest_is_cbd: boolean;
}

export interface OdMatrix {
  name: string;
  units: string;
  model: string;
  interpretation: string;
  pairs: OdPair[];
}

/**
 * Load the synthetic origin–destination commute matrix. Loaded lazily (~0.4 MB)
 * only when an overlay that needs real demand asks for it. This is world input,
 * not a simulation result.
 */
export async function loadOdMatrix(signal?: AbortSignal): Promise<OdMatrix> {
  return fetchJson<OdMatrix>("od_pairs.json", signal);
}

/** Sum daily inflow (trip attraction) per destination zone from the OD matrix. */
export function inflowByZone(od: OdMatrix): Map<string, number> {
  const m = new Map<string, number>();
  for (const p of od.pairs) {
    m.set(p.destination, (m.get(p.destination) ?? 0) + p.daily_person_trips);
  }
  return m;
}

// ---------------------------------------------------------------------------
// Prebuilt 3D city (buildings + water), generated by data/generate_buildings.py
// ---------------------------------------------------------------------------

/** Building kinds, used only to pick a colour. */
export type BuildingKind =
  | "tower"
  | "office"
  | "podium"
  | "mixed"
  | "residential"
  | "industrial"
  | "lowrise"
  | "park";

/**
 * Compact per-building attributes. Short keys keep the ~1k-feature file small;
 * see the `schema` block inside `buildings.geojson` for the canonical wording.
 */
export interface BuildingProps {
  /** Zone id this footprint sits in. */
  z: string;
  /** Kind (drives colour only). */
  k: BuildingKind;
  /** Height in metres today (t = 0). */
  h: number;
  /** Metres added by year 10 under the do-nothing baseline. */
  dh: number;
  /** Extra metres by year 10 if the scenario invests in transit (TOD). */
  td: number;
  /** Year the building appears; 0 = already standing. */
  t0: number;
  /** 1 = this lot can become public realm under pedestrianisation. */
  g: 0 | 1;
  /** 1 = inside the charge cordon. */
  cbd: 0 | 1;
  /** Kilometres from the city centre. */
  d: number;
}

export type BuildingFeature = Feature<Polygon, BuildingProps>;

export interface WaterProps {
  name: string;
  kind: string;
}

/** One real-world dataset the synthetic city is modelled on. */
export interface SourceRef {
  id: string;
  role: string;
  name: string;
  full_name?: string;
  publisher: string;
  country?: string;
  url: string;
  docs?: string;
  license: string;
  formats?: string[];
  how_used: string;
}

export interface SourcesDoc {
  title: string;
  note: string;
  sources: SourceRef[];
  model: {
    name: string;
    class: string;
    inputs: string[];
    mechanism: string;
    counts: Record<string, number>;
  };
}

/** Everything the 3D scene renders. Loaded once, then morphed client-side. */
export interface SceneData {
  geometry: CityGeometry;
  buildings: FeatureCollection<Polygon, BuildingProps>;
  water: FeatureCollection<Polygon, WaterProps>;
  od: OdMatrix;
  sources: SourcesDoc;
}

/**
 * Load the prebuilt 3D city: analytical geometry, building footprints with
 * their 10-year pipeline, the river, the OD matrix and the data lineage.
 *
 * All of it is static under `public/city/`, so the scene renders (and the
 * timeline scrubs) with the backend completely down.
 */
export async function loadCityScene(signal?: AbortSignal): Promise<SceneData> {
  const [geometry, buildings, water, od, sources] = await Promise.all([
    loadCityGeometry(signal),
    fetchJson<FeatureCollection<Polygon, BuildingProps>>(
      "buildings.geojson",
      signal,
    ),
    fetchJson<FeatureCollection<Polygon, WaterProps>>("water.geojson", signal),
    loadOdMatrix(signal),
    fetchJson<SourcesDoc>("sources.json", signal),
  ]);
  return { geometry, buildings, water, od, sources };
}
